import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const sharp=require('/Users/meltucker/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const dir=path.dirname(fileURLToPath(import.meta.url));
const src=path.join(dir,'assets','mat-ishbia-uwm-proxy-2024.jpg');
const output=path.join(dir,'assets','og-suns-signal-011-words-behind-work-v1.png');
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const bg=Buffer.from(`<svg width="1200" height="630" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#10151e"/><stop offset=".58" stop-color="#202631"/><stop offset="1" stop-color="#442617"/></linearGradient><linearGradient id="c" x1="0" y1="0" x2="1"><stop stop-color="#b85122"/><stop offset="1" stop-color="#f0a04b"/></linearGradient></defs><rect width="1200" height="630" fill="url(#g)"/><circle cx="968" cy="335" r="259" fill="none" stroke="#ba5c2c" stroke-width="2" opacity=".55"/><circle cx="968" cy="335" r="218" fill="#1b2028" stroke="#f4b273" stroke-width="4"/><path d="M0 579 L1200 579" stroke="#e0853b" opacity=".7"/><path d="M0 96 L1200 96" stroke="#ffffff" opacity=".15"/><text x="56" y="65" font-family="Arial,sans-serif" font-weight="800" font-size="28" fill="#fff">SUNS SIGNAL</text><text x="56" y="82" font-family="Arial,sans-serif" font-size="12" letter-spacing="2.2" fill="#f0a04b">ISSUE 011  /  MAT ISHBIA</text><text x="55" y="245" font-family="Arial,sans-serif" font-weight="800" font-size="74" fill="#fff">THE STANDARD</text><text x="55" y="326" font-family="Arial,sans-serif" font-weight="800" font-size="74" fill="#fff">IN HIS OWN</text><text x="55" y="407" font-family="Arial,sans-serif" font-weight="800" font-size="74" fill="#fff">WORDS</text><rect x="55" y="440" width="139" height="5" fill="url(#c)"/><text x="55" y="488" font-family="Arial,sans-serif" font-size="26" fill="#e5e7eb">Care. Culture. Roles. Accountability.</text><text x="55" y="613" font-family="Arial,sans-serif" font-size="16" letter-spacing="1.3" fill="#9daab8">ACCELERATED VELOCITY CONSULTING</text><text x="1140" y="613" text-anchor="end" font-family="Arial,sans-serif" font-size="14" fill="#9daab8">27 SEP 2026</text></svg>`);
const portrait=await sharp(src).resize(389,389,{fit:'cover'}).png().toBuffer();
const mask=Buffer.from(`<svg width="389" height="389" xmlns="http://www.w3.org/2000/svg"><circle cx="194.5" cy="194.5" r="190" fill="white"/></svg>`);
const masked=await sharp(portrait).composite([{input:mask,blend:'dest-in'}]).png().toBuffer();
await sharp(bg).composite([{input:masked,left:774,top:141}]).png().toFile(output);
const {width,height,channels}=await sharp(output).metadata();
if(width!==1200||height!==630||channels<3)throw new Error('Invalid OG size');
console.log(output);
